# Generated by Django 5.2.4 on 2025-07-31 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "isbn",
                    models.CharField(max_length=17, primary_key=True, serialize=False),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(default="")),
                ("author", models.CharField(max_length=255)),
                ("publishedDate", models.DateField()),
            ],
        ),
    ]
