# Generated by Django 5.2.4 on 2025-07-31 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_rename_publisheddate_book_published_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="book",
            name="isbn",
            field=models.CharField(max_length=17, unique=True),
        ),
    ]
