@hostname=localhost
# local testing port
@port=8000
# exposed service port on kubernetes
# @port=8081 
@host=http://{{hostname}}:{{port}}

# Health check
GET {{host}}/api/

###

# Get all books
GET {{host}}/api/books/
Accept: application/json

###

# Get book by id
GET {{host}}/api/books/2/
Accept: application/json

###

# Insert book
POST {{host}}/api/books/
Content-Type: application/json

{
    "isbn": "44-444-444-444-44",
    "title": "Dummy Book",
    "description": "This is a dummy description",
    "author": "Swan",
    "published_date": "2025-07-31"
}

###

# Update book (whole)
PUT {{host}}/api/books/2/
Content-Type: application/json

{
  "isbn": "11-111-111-111-11",
  "title": "Dune 1",
  "description": "Only the best book ever. Let the spice flow",
  "author": "Frank Herbert",
  "published_date": "2025-05-25"
}

###

# Update book (partial)
PATCH {{host}}/api/books/2/
Content-Type: application/json

{
  "description": "Updated description"
}

###

# Delete book
DELETE {{host}}/api/books/1/